# Generated by Django 2.2.16 on 2023-03-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedModel',
        ),
    ]
